% Copyright 2026 The MathWorks, Inc.

classdef TerminalThemes
    %TERMINALTHEMES Theme presets and utilities for Terminal.
    %
    %   Built-in presets:
    %     "dark", "light", "dracula", "monokai", "solarized-dark",
    %     "solarized-light", "nord", "gruvbox-dark", "one-dark",
    %     "tokyo-night", "catppuccin-mocha"
    %
    %   internal.TerminalThemes.list()           — list available preset names
    %   internal.TerminalThemes.resolve(theme)   — resolve a theme value to a full config struct
    %   internal.TerminalThemes.validate(theme)  — validate a theme value

    methods (Static)
        function names = list()
            %LIST Return available theme names including "auto".
            presets = internal.TerminalThemes.presets();
            names = ["auto"; string(fieldnames(presets))];
        end

        function validate(theme)
            %VALIDATE Error if theme is not a valid preset name or struct.
            if isstruct(theme)
                internal.TerminalThemes.validateStruct(theme);
                return;
            end
            if ~isstring(theme) && ~ischar(theme)
                error('Terminal:InvalidTheme', ...
                    'Theme must be a string or struct.');
            end
            theme = string(theme);
            normalized = strrep(theme, '-', '_');
            presets = internal.TerminalThemes.presets();
            validNames = ["auto"; string(fieldnames(presets))];
            normalizedNames = strrep(validNames, '-', '_');
            if ~ismember(normalized, normalizedNames)
                error('Terminal:InvalidTheme', ...
                    'Unknown theme "%s". Valid themes: %s, or pass a struct.', ...
                    theme, strjoin(validNames, ', '));
            end
        end

        function themeConfig = resolve(theme)
            %RESOLVE Resolve a theme value to a full config struct.
            %   Handles "auto", named presets, and custom structs.
            %   Adds font settings from MATLAB preferences and computes isDark.

            [fontFamily, fontSize] = internal.TerminalThemes.resolveFont();

            % --- Resolve colors ---
            presets = internal.TerminalThemes.presets();

            if isstruct(theme)
                % Custom struct: merge over dark defaults.
                colors = presets.dark;
                flds = fieldnames(theme);
                for i = 1:numel(flds)
                    colors.(flds{i}) = theme.(flds{i});
                end
            elseif string(theme) == "auto"
                % Detect dark/light mode.
                isDark = false;
                try
                    % Preferred: use MATLAB appearance setting (R2025a+).
                    s = settings;
                    currentTheme = string(s.matlab.appearance.CurrentTheme.ActiveValue);
                    isDark = contains(currentTheme, "dark", 'IgnoreCase', true);
                catch
                    % Fallback: infer from figure background luminance.
                    try
                        c = get(groot, 'defaultFigureColor');
                        luminance = 0.2126*c(1) + 0.7152*c(2) + 0.0722*c(3);
                        isDark = luminance < 0.5;
                    catch
                    end
                end
                if isDark
                    colors = presets.dark;
                else
                    colors = presets.light;
                end
            else
                % Named preset.
                normalized = strrep(string(theme), '-', '_');
                if isfield(presets, normalized)
                    colors = presets.(normalized);
                else
                    colors = presets.dark;
                end
            end

            % Compute isDark from resolved background.
            hex = colors.background;
            rgb = sscanf(hex(2:end), '%2x%2x%2x') / 255;
            colors.isDark = (0.2126*rgb(1) + 0.7152*rgb(2) + 0.0722*rgb(3)) < 0.5;

            % Attach font settings.
            colors.fontFamily = fontFamily;
            colors.fontSize = fontSize;

            themeConfig = colors;
        end
    end

    properties (Constant, Access = private)
        VALID_FIELDS = ["background", "foreground", "cursor", "cursorAccent", ...
            "selectionBackground", ...
            "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white", ...
            "brightBlack", "brightRed", "brightGreen", "brightYellow", ...
            "brightBlue", "brightMagenta", "brightCyan", "brightWhite"]
    end

    methods (Static, Access = private)
        function validateStruct(theme)
            %VALIDATESTRUCT Validate a custom theme struct.
            %   Checks that all field names are recognized and all values
            %   are valid '#rrggbb' hex color strings.
            flds = fieldnames(theme);
            for i = 1:numel(flds)
                f = string(flds{i});
                if ~ismember(f, internal.TerminalThemes.VALID_FIELDS)
                    error('Terminal:InvalidTheme', ...
                        'Unknown theme field "%s".\nValid fields: %s', ...
                        f, strjoin(internal.TerminalThemes.VALID_FIELDS, ', '));
                end
                val = theme.(flds{i});
                if ~ischar(val) && ~isstring(val)
                    error('Terminal:InvalidTheme', ...
                        'Theme field "%s" must be a hex color string (e.g., ''#ff0000'').', f);
                end
                val = string(val);
                if isempty(regexp(val, '^#[0-9a-fA-F]{6}$', 'once'))
                    error('Terminal:InvalidTheme', ...
                        'Theme field "%s" has invalid value "%s". Use ''#rrggbb'' hex format.', f, val);
                end
            end
        end

        function [fontFamily, fontSize] = resolveFont()
            %RESOLVEFONT Read font family and size from MATLAB code font settings.
            %   Returns CSS-ready fontFamily string and fontSize in CSS pixels.
            %   Falls back to sensible defaults if settings are unavailable.
            defaultFamily = 'Consolas, ''DejaVu Sans Mono'', ''Liberation Mono'', monospace';
            fontFamily = defaultFamily;
            fontSize = 14;

            try
                s = settings;
                fontSize = s.matlab.fonts.codefont.Size.ActiveValue;
            catch e
                warning('Terminal:FontSettings', ...
                    'Could not read code font size from MATLAB settings: %s\nUsing default %dpt.', ...
                    e.message, fontSize);
            end

            try
                userFont = char(s.matlab.fonts.codefont.Name.ActiveValue);
                fontFamily = ['''' userFont ''', ' defaultFamily];
            catch e
                warning('Terminal:FontSettings', ...
                    'Could not read code font name from MATLAB settings: %s\nUsing default font family.', ...
                    e.message);
            end

            % Convert typographic points to CSS pixels on platforms that
            % use standard typographic points (1pt = 1/72 inch).
            %
            % macOS: MATLAB follows Apple's convention where font size
            % values map directly to CSS pixels (rooted in the classic
            % 72 PPI model).  No conversion needed.
            %
            % Windows/Linux: MATLAB uses standard typographic points,
            % so we convert to CSS pixels (1px = 1/96 inch) via 96/72.
            %
            % We intentionally do NOT use ScreenPixelsPerInch here.
            % The xterm.js fontSize is in CSS pixels, which are
            % resolution-independent — the browser/webview handles
            % devicePixelRatio / Retina / HiDPI scaling on its own.
            % Using platform-reported PPI would double-count that scaling.
            if ~ismac
                fontSize = round(fontSize * 96 / 72);
            end
        end

        function p = presets()
            %PRESETS Return a struct of all built-in theme presets.
            persistent cache
            if ~isempty(cache)
                p = cache;
                return;
            end

            cache.dark = struct( ...
                'background',  '#1e1e1e', ...
                'foreground',  '#d4d4d4', ...
                'cursor',      '#aeafad', ...
                'selectionBackground', '#264f78');

            cache.light = struct( ...
                'background',  '#ffffff', ...
                'foreground',  '#333333', ...
                'cursor',      '#333333', ...
                'selectionBackground', '#add6ff');

            cache.dracula = struct( ...
                'background',  '#282a36', ...
                'foreground',  '#f8f8f2', ...
                'cursor',      '#f8f8f2', ...
                'selectionBackground', '#44475a', ...
                'black',       '#21222c', ...
                'red',         '#ff5555', ...
                'green',       '#50fa7b', ...
                'yellow',      '#f1fa8c', ...
                'blue',        '#bd93f9', ...
                'magenta',     '#ff79c6', ...
                'cyan',        '#8be9fd', ...
                'white',       '#f8f8f2', ...
                'brightBlack', '#6272a4', ...
                'brightRed',   '#ff6e6e', ...
                'brightGreen', '#69ff94', ...
                'brightYellow','#ffffa5', ...
                'brightBlue',  '#d6acff', ...
                'brightMagenta','#ff92df', ...
                'brightCyan',  '#a4ffff', ...
                'brightWhite', '#ffffff');

            cache.monokai = struct( ...
                'background',  '#272822', ...
                'foreground',  '#f8f8f2', ...
                'cursor',      '#f8f8f0', ...
                'selectionBackground', '#49483e', ...
                'black',       '#272822', ...
                'red',         '#f92672', ...
                'green',       '#a6e22e', ...
                'yellow',      '#f4bf75', ...
                'blue',        '#66d9ef', ...
                'magenta',     '#ae81ff', ...
                'cyan',        '#a1efe4', ...
                'white',       '#f8f8f2', ...
                'brightBlack', '#75715e', ...
                'brightRed',   '#f92672', ...
                'brightGreen', '#a6e22e', ...
                'brightYellow','#f4bf75', ...
                'brightBlue',  '#66d9ef', ...
                'brightMagenta','#ae81ff', ...
                'brightCyan',  '#a1efe4', ...
                'brightWhite', '#f9f8f5');

            cache.solarized_dark = struct( ...
                'background',  '#002b36', ...
                'foreground',  '#839496', ...
                'cursor',      '#839496', ...
                'selectionBackground', '#073642', ...
                'black',       '#073642', ...
                'red',         '#dc322f', ...
                'green',       '#859900', ...
                'yellow',      '#b58900', ...
                'blue',        '#268bd2', ...
                'magenta',     '#d33682', ...
                'cyan',        '#2aa198', ...
                'white',       '#eee8d5', ...
                'brightBlack', '#586e75', ...
                'brightRed',   '#cb4b16', ...
                'brightGreen', '#586e75', ...
                'brightYellow','#657b83', ...
                'brightBlue',  '#839496', ...
                'brightMagenta','#6c71c4', ...
                'brightCyan',  '#93a1a1', ...
                'brightWhite', '#fdf6e3');

            cache.solarized_light = struct( ...
                'background',  '#fdf6e3', ...
                'foreground',  '#657b83', ...
                'cursor',      '#657b83', ...
                'selectionBackground', '#eee8d5', ...
                'black',       '#073642', ...
                'red',         '#dc322f', ...
                'green',       '#859900', ...
                'yellow',      '#b58900', ...
                'blue',        '#268bd2', ...
                'magenta',     '#d33682', ...
                'cyan',        '#2aa198', ...
                'white',       '#eee8d5', ...
                'brightBlack', '#002b36', ...
                'brightRed',   '#cb4b16', ...
                'brightGreen', '#586e75', ...
                'brightYellow','#657b83', ...
                'brightBlue',  '#839496', ...
                'brightMagenta','#6c71c4', ...
                'brightCyan',  '#93a1a1', ...
                'brightWhite', '#fdf6e3');

            cache.nord = struct( ...
                'background',  '#2e3440', ...
                'foreground',  '#d8dee9', ...
                'cursor',      '#d8dee9', ...
                'selectionBackground', '#434c5e', ...
                'black',       '#3b4252', ...
                'red',         '#bf616a', ...
                'green',       '#a3be8c', ...
                'yellow',      '#ebcb8b', ...
                'blue',        '#81a1c1', ...
                'magenta',     '#b48ead', ...
                'cyan',        '#88c0d0', ...
                'white',       '#e5e9f0', ...
                'brightBlack', '#4c566a', ...
                'brightRed',   '#bf616a', ...
                'brightGreen', '#a3be8c', ...
                'brightYellow','#ebcb8b', ...
                'brightBlue',  '#81a1c1', ...
                'brightMagenta','#b48ead', ...
                'brightCyan',  '#8fbcbb', ...
                'brightWhite', '#eceff4');

            cache.gruvbox_dark = struct( ...
                'background',  '#282828', ...
                'foreground',  '#ebdbb2', ...
                'cursor',      '#ebdbb2', ...
                'selectionBackground', '#3c3836', ...
                'black',       '#282828', ...
                'red',         '#cc241d', ...
                'green',       '#98971a', ...
                'yellow',      '#d79921', ...
                'blue',        '#458588', ...
                'magenta',     '#b16286', ...
                'cyan',        '#689d6a', ...
                'white',       '#a89984', ...
                'brightBlack', '#928374', ...
                'brightRed',   '#fb4934', ...
                'brightGreen', '#b8bb26', ...
                'brightYellow','#fabd2f', ...
                'brightBlue',  '#83a598', ...
                'brightMagenta','#d3869b', ...
                'brightCyan',  '#8ec07c', ...
                'brightWhite', '#ebdbb2');

            cache.one_dark = struct( ...
                'background',  '#282c34', ...
                'foreground',  '#abb2bf', ...
                'cursor',      '#528bff', ...
                'selectionBackground', '#3e4451', ...
                'black',       '#545862', ...
                'red',         '#e06c75', ...
                'green',       '#98c379', ...
                'yellow',      '#e5c07b', ...
                'blue',        '#61afef', ...
                'magenta',     '#c678dd', ...
                'cyan',        '#56b6c2', ...
                'white',       '#abb2bf', ...
                'brightBlack', '#545862', ...
                'brightRed',   '#e06c75', ...
                'brightGreen', '#98c379', ...
                'brightYellow','#e5c07b', ...
                'brightBlue',  '#61afef', ...
                'brightMagenta','#c678dd', ...
                'brightCyan',  '#56b6c2', ...
                'brightWhite', '#c8ccd4');

            cache.tokyo_night = struct( ...
                'background',  '#1a1b26', ...
                'foreground',  '#a9b1d6', ...
                'cursor',      '#c0caf5', ...
                'selectionBackground', '#33467c', ...
                'black',       '#15161e', ...
                'red',         '#f7768e', ...
                'green',       '#9ece6a', ...
                'yellow',      '#e0af68', ...
                'blue',        '#7aa2f7', ...
                'magenta',     '#bb9af7', ...
                'cyan',        '#7dcfff', ...
                'white',       '#a9b1d6', ...
                'brightBlack', '#414868', ...
                'brightRed',   '#f7768e', ...
                'brightGreen', '#9ece6a', ...
                'brightYellow','#e0af68', ...
                'brightBlue',  '#7aa2f7', ...
                'brightMagenta','#bb9af7', ...
                'brightCyan',  '#7dcfff', ...
                'brightWhite', '#c0caf5');

            cache.catppuccin_mocha = struct( ...
                'background',  '#1e1e2e', ...
                'foreground',  '#cdd6f4', ...
                'cursor',      '#f5e0dc', ...
                'selectionBackground', '#45475a', ...
                'black',       '#45475a', ...
                'red',         '#f38ba8', ...
                'green',       '#a6e3a1', ...
                'yellow',      '#f9e2af', ...
                'blue',        '#89b4fa', ...
                'magenta',     '#f5c2e7', ...
                'cyan',        '#94e2d5', ...
                'white',       '#bac2de', ...
                'brightBlack', '#585b70', ...
                'brightRed',   '#f38ba8', ...
                'brightGreen', '#a6e3a1', ...
                'brightYellow','#f9e2af', ...
                'brightBlue',  '#89b4fa', ...
                'brightMagenta','#f5c2e7', ...
                'brightCyan',  '#94e2d5', ...
                'brightWhite', '#a6adc8');

            p = cache;
        end
    end
end
